title: "クラウドプラットフォーム詳細比較"
description: "次期データ分析基盤の候補となる主要クラウド 3 社を 6 観点で比較する"
headers: 
  - "評価軸"
  - "AWS"
  - "Azure"
  - "Google Cloud"
rows:
  - ["価格モデル", "従量＋リザーブ", "従量＋予約インスタンス", "従量のみ（割引多）"]
  - ["サービス範囲", "IaaS/PaaS/SaaS 全網羅", "IaaS/PaaS/SaaS", "IaaS/PaaS 中心"]
  - ["セキュリティ認証数", "26", "38", "19"]
  - ["リージョン数", "31", "54", "35"]
  - ["機械学習サービスの成熟度", "高", "中", "高"]
  - ["パートナーエコシステム", "8,000+", "7,000+", "6,000+"]
improvements:
  - ""
  - ""
  - "最多認証"
  - "最多リージョン"
  - ""
  - "最大エコシステム"
notes:
  - "セキュリティ認証は 2025-06 時点の公式発表ベース"
  - "機械学習は AutoML・LLM サービスを含む"
  - "価格は東日本リージョン vCPU/GB 単価で比較"
